name: "Intelligent CI-CD Pipelines"

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:  
  SAST-Analysis:
    name: SAST Analysis (CodeQL)
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Permissão necessária para o CodeQL enviar os resultados
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          # O CodeQL suporta 'javascript', 'python', 'go', 'java', 'csharp', 'cpp', 'ruby', 'swift'
          # Para o Juice Shop, que é baseado em Node.js, usamos 'javascript'.
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  Build-and-Deploy:
    name: Build and Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: . # Path to the build context (where your Dockerfile is)
      #     push: true # Set to false if you only want to build, not push
      #     tags: avnermiguel/mba-intelligent-ci-cd-pipelines:latest # Image tags
      #     # cache-from: type=registry,ref=your-docker-username/your-image-name:cache # Optional: use registry cache
      #     # cache-to: type=registry,ref=your-docker-username/your-image-name:cache,mode=max # Optional: push cache to registry

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ vars.AWS_REGION }}
          application_name: ${{ vars.AWS_APPLICATION_NAME }} # Substitua pelo nome do seu Application
          environment_name: ${{ vars.AWS_ENVIRONMENT_NAME }} # Substitua pelo nome do seu Environment
          version_label: ${{ github.sha }}
          deployment_package: Dockerrun.aws.json # Indica que o pacote de deploy é este arquivo

      - name: Run container and test health
        run: |
          docker run -d -p 3000:3000 --name app avnermiguel/mba-intelligent-ci-cd-pipelines:latest
          sleep 5
          curl -f http://localhost:3000/ || (docker logs app && exit 1)